export const RECEIVE_ALARMS = 'RECEIVE_ALARMS'
export const SORT_ALARMS = 'SORT_ALARMS'
export const ADD_ALARM = 'ADD_ALARM'
export const UPDATE_ALARM = 'UPDATE_ALARM'
export const DELETE_ALARM = 'DELETE_ALARM'

export const SET_RADIO_STATE = 'SET_RADIO_STATE'

export const RECEIVE_RADIO_STATIONS = 'RECEIVE_RADIO_STATIONS'
export const SORT_RADIO_STATIONS = 'SORT_RADIO_STATIONS'
export const ADD_RADIO_STATION = 'ADD_RADIO_STATION'
export const UPDATE_RADIO_STATION = 'UPDATE_RADIO_STATION'
export const DELETE_RADIO_STATION = 'DELETE_RADIO_STATION'

export const SET_LIGHT = 'SET_LIGHT'
